### PR TITLE
expanding documentation

### PR DESCRIPTION
**Pull request by Vankog**
I had some issues understanding the setup.

### CODE REVIEW

**Comment by dail8859** [comment]
Thanks for this PR. I tweaked it a bit before committing but it is nice to get a user perspective :) Also, I didn't know about the BugTraq integration, so that documentation is good to have there as well.

**Comment by Vankog** [comment]
Yeah I didn't know about that, too, until I checked the TortoiseGit help. I think it's the better method, because its much more flexible, you just need the GUID and the parameters. 
I also use the regex matcher of BugTraq to complement the plugin, e.g. I added these values locally to my TurtleHub fork (i.e. it will be saved to the \.git\config file):
```
[bugtraq]
	url = https://github.com/dail8859/TurtleHub/issues/%BUGID%
	warnifnoissue = true
	logregex = "\\S+\\/\\S+#(\\d+)"
	providerparams = "owner=dail8859;repository=TurtleHub;keyword=<None>;reffullrepo=True"
	provideruuid64 = {B2C6EC0F-8742-4792-9FDC-10635D2C118B}
```
bugtraq

But I think you might as well add these to your project scope with the .tgitconfig file.
This way all forks can benefit from it and you can also provide a practical example about how to use it.

btw: Is the GUID always the same? If so, you might as well provide it in the readme.

**Comment by dail8859** [comment]
> Is the GUID always the same?

Yes I believe this is the case as long as you don't switch between x64 and x86. Updates to the plugin (e.g. `v0.2` -> `v0.3`) keep the same GUID. I copied a lot of this code from [Gurtle](https://code.google.com/archive/p/gurtle/) (the old plugin for Google Code) so there are parts of it I'm not too familiar with.

**Comment by Vankog** [comment]
Ah, GUID (Globally Unique) is just another word for UUID (Universally Unique). So it seems you just generate a random one and stick with it. So you can easily add the two to the readme.

**Pull request closed without merging**
