### PR TITLE
adding project-scope BugTraq config and readme

### PR DESCRIPTION
**Pull request by Vankog**
for log-linking as well as TurtleHub integration.

This gives detailed information about how to integrate TurtleHub with BugTraq in a shared environment.

I think this `.tgitconfig` should be integrated into this repo as an example. I chose the extended notation, because forks can work with this out of the box as well.

### CODE REVIEW

**Comment by Vankog** [comment]
Ah, I forgot to mention that it is easily possible to overwrite the project-scope config locally, without changing the project file. 
e.g. I enabled the warning on local level. 
But you might also add a keyword.

**Comment by dail8859** [comment]
This additional information is good to have but I feel it clutters up the readme too much and makes it harder to follow. I think most users will just use the local integration anyways since it is easier to get started this way. 

This information would probably better in a separate markdown document or wiki page (and have the readme link to it). That way users that want to do a more advanced configuration can still reference it.

**Comment by Vankog** [comment]
I had a feeling you might say this. I'll have a look at how to separate it into another file.

**Comment by Vankog** [comment]
Alright @dail8859 , how about this?
Just look at my branch to see everything at a glance:
https://github.com/Vankog/TurtleHub/tree/BugTraq 

I moved the setup instructions into a seperate file in /docs and moved the images in there, too. The Readme just delegates to the according section after introducing both methods.

Todo:
- [ ] If the new release is out we only have to update some screenshots to match the new parameter checkbox.

**Comment by dail8859** [comment]
Sorry for the delay. I looked over it briefly. In the readme I think the 4 steps for the local integration should still be included. This will be what most people use and the steps are simple to get someone started using Turtle hub. The current way in the PR always requires someone to go to the Setup.md file. All the sub-bullets under step 4 can still stay in the Setup.md file incase the user wants more details about the settings.

Also, whatever editor you are using is hard wrapping the text which clutters up the diffs alot. :)

**Comment by Vankog** [comment]
I see. OK I'll add a kind of "quick start" to the readme.

About the wrapping:
Yeah, I did this on purpose. It's a kind of compulsion to stay in the common line width limits. ^^
If you care, I can revert the line breaks.

**Comment by Vankog** [comment]
Alright, how about this?

direct links for complete view:  
https://github.com/Vankog/TurtleHub/blob/BugTraq/README.md  
https://github.com/Vankog/TurtleHub/blob/BugTraq/docs/Setup.md

**Comment by dail8859** [comment]
Hi @Vankog,

Sorry for the long delay. I appreciate the effort you've gone to for this PR (and I'm sure others reading it will too). I'll go ahead and squash+merge this in since it looks fine...and hopefully get a new release out soon. :)

**Pull request merged**
