### PR TITLE
Add GitLab Issue Tracker support

### PR DESCRIPTION
**Pull request by Maxhy**
This PR do several major changes:
 - It bumps Visual Studio version from 2015 to 2017 (because of better .netstandard support)
 - It changes target .NET Framework version from v4.5 to v4.6.1 (again because of .netstandard, 2.0 here)
 - And mainly, it adds generic abstraction on Issue Tracker to add GitLab (https://gitlab.com) for those having their own Git repositories on a GitLab server.

I know current scope of TurtleHub is GitHub only but this would avoid forking the project just to add another git-based issue tracker highly similar to GitHub.

### CODE REVIEW

**Comment by dail8859** [comment]
You'll have to bear with me a bit because I'm not incredibly experienced with it comes to C# :)

> It bumps Visual Studio version from 2015 to 2017 (because of better .netstandard support)
> It changes target .NET Framework version from v4.5 to v4.6.1 (again because of .netstandard, 2.0 here)

All my development is currently done with 2015 and I don't have any immediate plans to move to 2017, so if at all possible I'd like to stick to 2015. That being said I was able to get this working with some minor tweaks. For the GitLabApiClient and Newtonsoft.Json package I just set the `targetFramework` to net45 (not sure if this was needed or not) and I had to reference the `netstandard` 2.0 and then I was able to build it.

> I know current scope of TurtleHub is GitHub only but this would avoid forking the project just to add another git-based issue tracker highly similar to GitHub.

I agree that forking the project probably would not make sense because there would be very little code that would need changed (which this PR makes very clear). I think in the end having them in the same project makes the most sense. Plus for users that use Github and Gitlab it is a single install...and in the future other trackers could possibly be added. 

When I get some more time I'll look into this PR more.

**Comment by dail8859** [comment]
I looked over this briefly and it looks good for the most part. I haven't tested this with GitLab at all yet.

Couple things I noticed:
- Fetching issues from a GitHub repo with alot of issues waits until *all* the issues are fetched before displaying any. This is because `GetAllIssuesOnRepository()` doesn't return until all of them are ready. Previously it would make a request (50 being the max at a time for GitHub), stick them in the list to display them, then make the next request. Not sure the best way to go about solving this problem, maybe make `GetAllIssuesOnRepository()` yield multiple `IReadOnlyList<TurtleIssue>` somehow?
- The options dialog might need some tweaking but I'm not sure of any concrete suggestions. I'll have to give this more thought. I know since I'm strictly a GitHub'er I was a little thrown off by allowing a custom URL but since GitLab can be hosted easily then a custom URL makes sense.

Some questions/comments/thinking out loud:
- Does GitLab *require* an API token? GitHub does not but you are limited to a small number of requests/hour you can make. As you've seen in the code I have an undocumented way to do authenticated requests for GitHub. I'm not real comfortable about storing user's tokens in plain-text. Ideally there is some way to store them securely, or maybe just not store them at all to avoid any security problems?
- I'm still a little on the fence about adding GitLab support to Turtle*Hub*. However, completely splitting the project would not make sense. So I see a few options:
    1. Split/fork the project and have TurtleHub and something like TurtleLab. This wouldn't be that great as there would be little code difference between the two, and any changes to the core of one would need made to the other
    1. Add GitLab support to TurtleHub and hope that users don't get confused that Turtle*Hub* also supports GitLab (and maybe others in the future?). Also it might install a few extra DLLs that people aren't interested in...not a big deal.
    1. Add GitLab support to this repository, but create separate installers for GitHub and GitLab support (e.g. TurtleHub and TurtleLab installers). It might help user's differentiate the support for multiple trackers. But in the end if there is so little difference why not go with option `ii` above.

**Comment by dail8859** [comment]
So far I've had 0 luck getting this to work with GitLab. Not sure if I'm doing something wrong or the fact I'm using VS2015 and .NET Framework version v4.5. I'm using settings such as:

capture

And getting exceptions like this:

```
GitLabApiClient.GitLabException
   at GitLabApiClient.Internal.Http.GitLabApiRequestor.<EnsureSuccessStatusCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitLabApiClient.Internal.Http.GitLabApiRequestor.<GetWithHeaders>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitLabApiClient.Internal.Http.GitLabApiPagedRequestor.<GetPagedList>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitLabApiClient.ProjectsClient.<GetAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TurtleHub.GitLabIssueTracker.<GetAllIssuesOnRepository>d__3.MoveNext() in C:\Users\xxx\Code\TurtleHub\src\TurtleHub\GitLabIssueTracker.cs:line 28
```

And gives me a 308 HTTP response code...not sure where it is trying to redirect me to.

**Comment by Maxhy** [comment]
Indeed for `GetAllIssuesOnRepository`. I will update my PR later this week to have something working as previously.
About your thoughts:
 * GitLab requires an API Token. Having it as a visible option on the plugin setup is not really a big deal in my opinion. That's the problem with API token...
 * I'm in favor of adding extra dll. We can still split it later if there is more issue tracker implementation.

No luck with gitlab.com neither, only with custom GitLab servers I don't know why yet...

**Comment by Vankog** [comment]
> I'm still a little on the fence about adding GitLab support to TurtleHub. However, completely splitting the project would not make sense. So I see a few options:

What about some kind of plugin system? TurtleHub is an issue provider for the Tortoise VCS family. Why not going a step farther and splitting the architecture into a base and several plugins (github, gitlab, any others)? I know it might be a major refactoring, though.

**Comment by dail8859** [comment]
> What about some kind of plugin system?

I had thought about something like that, but not sure if that makes sense either. The "base" part would end up being a little bit of glue code with a couple dialogs...and the plugins are pretty much just thin wrappers around whatever API is required to fetch the issues. (Thinking out load) Would the base + any plugins be all separate installers? I guess maybe a single installer with options to select what kind of issue tracker integration the user wants...but then again the way you register issue trackers with TortoiseGit doesn't really play nice with this kind of flexibility...

There is enough commonality between these two issue trackers (and potentially others in the future) that it is definitely best to integrate the code into this project somehow...the important question is how to package it and make sure users understand what it the plugin offers (e.g. TurtleHub == Github support).

**Comment by Vankog** [comment]
I think it should be separate.
TurtleHub is explicitly for adding Github issues to Tortoise.
A possible "TurtleLab" should be explicitly for Gitlab issues. 
However, TurtleLab and others (e.g. Bitbucket) might be explicit downstreams of TurtleHub. This way changes can be implemented quite easily for all downstreams.

You can advertise all the Spin-Offs somewhere, so users can choose themselves.

EDIT: What about a separate "TurtleX Installer" project?
It is used as a common denominator which lets the user choose the package he/she wants and downloads and installs the appropriate project like TurtleHub or TurtleLab.

**Comment by dail8859** [comment]
> TurtleHub is explicitly for adding Github issues to Tortoise.
> A possible "TurtleLab" should be explicitly for Gitlab issues.

This is kind of what I'm thinking as well. This will make it clear which plugin supports which issue tracker, and users can pick and choose what they want.

> However, TurtleLab and others (e.g. Bitbucket) might be explicit downstreams of TurtleHub.

This is the hard part of deciding "where" to make the split. If each downstream implementation has to continually merge any changes from TurtleHub it might become a bit of a pain, and it is harder to guarantee the same "core" part of the plugin is common among the downstream implementations as they might start tweaking things themselves...though changes to this project are kind of slow and minor at this stage...so maybe this is a moot point.

> What about a separate "TurtleX Installer" project?

If more implementations start to build off of TurtleHub, then I think something like this might be a good idea.

---

So...for now this is what I'm probably going with (feel free to comment/agree/disagree)...
- Integrate this PR into the "TurtleHub" repository
- Rework the code and build system internally (while still sharing as much code as possible between the two) to create separate installers (TurtleHub and TurtleLab).
- If more implementations start to happen...then reevaluate this way of doing it...and maybe go with a single "parent" installer and let the users pick and choose what they want. 

In general this project isn't overly active or used by alot of users. So trying to over-engineer a solution right now seems painful...so I think this way it will at least allow for the possibility to decide what to do later if more people extend the functionality.

**Comment by dail8859** [comment]
> Rework the code and build system internally (while still sharing as much code as possible between the two) to create separate installers (TurtleHub and TurtleLab).

I've made nice progress on this part of it with the current PR. Once this PR is updated/merged then I'll clean up what I have a bit and push everything to the main repo.

Then comes the hard part of creating a new logo for TurtleLab since I have 0 artistic abilities. :)

**Comment by Vankog** [comment]
May I ask for a preview build with the Gitlab integration if there is already something runnable available? :-)

**Comment by dail8859** [comment]
This PR does complie and ties into TortoiseGit but it doesn't actually work with GitLab yet as seen above. This still of interest to you?

**Comment by Vankog** [comment]
I see, I was just curious after having a look at the pr11 branch.
I recently got hold of two gitlab repositories through my work and was wondering how it was coming. 
But it seems it wouldn't help me anyway, because their issues are managed in Jira instead.

**Comment by dail8859** [comment]
The pr11 branch split some logic to start creating the two separate binaries but didn't add anything to the "GitLab" side of this PR.

**Comment by dail8859** [comment]
Closing due to inactivity.

**Pull request closed without merging**
